// <auto-generated />
namespace SofiaDayAndNight.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TablesConnectionsFixes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TablesConnectionsFixes));
        
        string IMigrationMetadata.Id
        {
            get { return "201710081419187_Tables Connections Fixes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
